USE sucos;

CREATE TABLE TABELA_DE_VENDEDORES (
        MATRICULA varchar(5) PRIMARY KEY,
        NOME varchar(100),
        PERCENTUAL_COMISSAO float,
        DATA_ADMISSAO DATE,
        DE_FERIAS BIT(1)
);

INSERT INTO tabela_de_vendedores (
MATRICULA,
NOME,
PERCENTUAL_COMISSAO,
DATA_ADMISSAO,
DE_FERIAS) VALUES (
'00235',
'Márcio Almeida Silva',
8,
'2014-08-15',
0);

INSERT INTO tabela_de_vendedores (
MATRICULA,
NOME,
PERCENTUAL_COMISSAO,
DATA_ADMISSAO,
DE_FERIAS) VALUES (
'00236',
'Cláudia Morais',
8,
'2013-09-17',
1);

INSERT INTO tabela_de_vendedores (
MATRICULA,
NOME,
PERCENTUAL_COMISSAO,
DATA_ADMISSAO,
DE_FERIAS) VALUES (
'00237',
'Roberta Martins',
11,
'2017-03-18',
1);

INSERT INTO tabela_de_vendedores (
MATRICULA,
NOME,
PERCENTUAL_COMISSAO,
DATA_ADMISSAO,
DE_FERIAS) VALUES (
'00238',
'Péricles Alves',
11,
'2016-08-21',
0);

SELECT * FROM tabela_de_vendedores;

